### ISSUE TITLE
Throws an exception when assigning a value to the `FontFamily` property of the `SfChip` control

### ISSUE THREAD

**Issue by egvijayanand** [syncfusion/maui-toolkit#12]
Throws an exception when assigning a value to the **FontFamily** property of the **SfChip** control

Exception message: **Value does not fall within the expected range.**

Toolkit version: **1.0.1**

.NET MAUI version: **8.0.92**

**Comment by PaulAndersonS** [comment]
hi @egvijayanand ,

We have investigated the reported issue with the SfChip FontFamily on our end. The problem occurs only in VS Code; it does not happen when running the application in Visual Studio 2022.
This is a known issue that we have documented within the framework. Please find the relevant issue links below:
[Maui Framework Issue [Link](https://github.com/dotnet/maui/issues/24609)]
[Windows Framework Issue [Link](https://github.com/microsoft/Win2D/issues/941)]

Reason:
The discrepancy may be due to differences between packaged and unpackaged applications. Unlike Visual Studio, which defaults to a packaged configuration, these details are explained in the Framework issue [link](https://github.com/dotnet/maui/issues/24609#issuecomment-2344244019)

**Comment by egvijayanand** [comment]
Seems this is not related to IDE as I encountered this issue in VS2022.

After going through the referenced issue, I understand that it's related to the App packaging type - Packaged or Unpacked.

The issue is with the Unpacked type. Hope it gets addressed once the core framework supports it.
