### ISSUE TITLE
Resize Issue Of TabView

### ISSUE THREAD

**Issue by OliveInto** [syncfusion/maui-toolkit#55]
### Description

Just consider a clean project with a large box view in second tab as a placeholder. If set EnableVirtualization=true and start, by default tabView will take place properly according to the size of the window, after switching to the second tab and go back to the first, the tabview will not shrink back, therefore the outer scrollview will show scroller.
If set EnableVirtualization=false, the first tab will take as much place as the second one. Thus the outer scroller will always be presented.
In my opinion, the tabview should try to fit the size of the outer control and expand only when it is necessary.

### Steps to Reproduce

```
<ContentPage
    x:Class="TabViewTest.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:tabView="clr-namespace:Syncfusion.Maui.Toolkit.TabView;assembly=Syncfusion.Maui.Toolkit">
    <ScrollView>
        <tabView:SfTabView EnableVirtualization="True">
            <tabView:SfTabItem Header="SomeControls">
                <Label Text="Only One Line" />
            </tabView:SfTabItem>
            <tabView:SfTabItem Header="ManyControls">
                <VerticalStackLayout Padding="30,0" Spacing="25">
                    <Image
                        Aspect="AspectFit"
                        HeightRequest="185"
                        SemanticProperties.Description="dot net bot in a hovercraft number nine"
                        Source="dotnet_bot.png" />

                    <Label
                        SemanticProperties.HeadingLevel="Level1"
                        Style="{StaticResource Headline}"
                        Text="Hello, World!" />

                    <Label
                        SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                        SemanticProperties.HeadingLevel="Level2"
                        Style="{StaticResource SubHeadline}"
                        Text="Welcome to &#10;.NET Multi-platform App UI" />
                    <Label Text="Large BoxView" />
                    <BoxView HeightRequest="800" />

                    <Button
                        x:Name="CounterBtn"
                        Clicked="OnCounterClicked"
                        HorizontalOptions="Fill"
                        SemanticProperties.Hint="Counts the number of times you click"
                        Text="Click me" />
                </VerticalStackLayout>
            </tabView:SfTabItem>
        </tabView:SfTabView>
    </ScrollView>
</ContentPage>
```

### Version with bug

1.0.2

### Is this a regression from previous behavior?

No, this is a new issue

### Last Known Working Version

1.0.2

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Have you found a workaround?

No

**Comment by OliveInto** [comment]
https://github.com/user-attachments/assets/abdf0515-a42f-42fa-aea3-4d3eeb373afa

**Comment by ArunachalamSyncfusion** [comment]
Hi @OliveInto,

Thanks for contacting Syncfusion support.

We have validated the reported issue where TabView's tab items do not receive the expected height based on each child when placed inside a ScrollView. In the TabView control, the HorizontalStackLayout is used to hold the content of each tab item as its child.

After thoroughly investigating this behavior, we found that when HorizontalStackLayout is placed inside a ScrollView, its height increases based on the child with the largest height. As a result, all other tab items appear to have the same height, and a scrollbar appears for all items. This behavior occurs because HorizontalStackLayout adopts the height of the largest tab item's content. We have demonstrated this behavior in the attached sample for your reference.

[MauiApp1.zip](https://github.com/user-attachments/files/18150978/MauiApp1.zip)

To resolve this, we recommend avoiding the use of TabView inside a ScrollView when you want each tab item's content to have its own height. Instead, if you have large content within any tab item, place the ScrollView inside the tab item's content. For your reference, we have attached the sample please take a look.

[TabViewSample.zip](https://github.com/user-attachments/files/18150994/TabViewSample.zip)

If you have any questions or require assistance, please feel free to contact us!

Regards,
Arunachalam K

**Comment by OliveInto** [comment]
@ArunachalamSyncfusion 
Thank you for help, I have checked the provided example. Since it is an expected behavior, I will close the issue.
